version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - mary-agency-network

  # Optional: Add Supabase local development
  # supabase:
  #   image: supabase/postgres:15.1.0.117
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: your-super-secret-and-long-postgres-password
  #     POSTGRES_DB: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - mary-agency-network

networks:
  mary-agency-network:
    driver: bridge

# volumes:
#   postgres_data: